/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace MultiSigBudget {
  export type BudgetStruct = {
    recipient: AddressLike;
    amount: BigNumberish;
    released: boolean;
    approvals: BigNumberish;
    timestamp: BigNumberish;
  };

  export type BudgetStructOutput = [
    recipient: string,
    amount: bigint,
    released: boolean,
    approvals: bigint,
    timestamp: bigint
  ] & {
    recipient: string;
    amount: bigint;
    released: boolean;
    approvals: bigint;
    timestamp: bigint;
  };
}

export interface MultiSigBudgetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approvals"
      | "approveBudget"
      | "budgets"
      | "getBudgetStatus"
      | "getBudgets"
      | "getmanagers"
      | "isManager"
      | "managers"
      | "proposeBudget"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BudgetApproved"
      | "BudgetProposed"
      | "BudgetReleased"
      | "Deposit"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approvals",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approveBudget",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "budgets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBudgetStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBudgets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getmanagers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "managers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeBudget",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "approvals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveBudget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "budgets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBudgetStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBudgets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getmanagers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isManager", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "managers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposeBudget",
    data: BytesLike
  ): Result;
}

export namespace BudgetApprovedEvent {
  export type InputTuple = [budgetId: BigNumberish, approver: AddressLike];
  export type OutputTuple = [budgetId: bigint, approver: string];
  export interface OutputObject {
    budgetId: bigint;
    approver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BudgetProposedEvent {
  export type InputTuple = [
    budgetId: BigNumberish,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    budgetId: bigint,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    budgetId: bigint;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BudgetReleasedEvent {
  export type InputTuple = [
    budgetId: BigNumberish,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    budgetId: bigint,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    budgetId: bigint;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositEvent {
  export type InputTuple = [sender: AddressLike, amount: BigNumberish];
  export type OutputTuple = [sender: string, amount: bigint];
  export interface OutputObject {
    sender: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MultiSigBudget extends BaseContract {
  connect(runner?: ContractRunner | null): MultiSigBudget;
  waitForDeployment(): Promise<this>;

  interface: MultiSigBudgetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approvals: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  approveBudget: TypedContractMethod<
    [_budgetId: BigNumberish],
    [void],
    "nonpayable"
  >;

  budgets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, boolean, bigint, bigint] & {
        recipient: string;
        amount: bigint;
        released: boolean;
        approvals: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getBudgetStatus: TypedContractMethod<
    [_budgetId: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        recipient: string;
        amount: bigint;
        approvalCount: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getBudgets: TypedContractMethod<
    [],
    [MultiSigBudget.BudgetStructOutput[]],
    "view"
  >;

  getmanagers: TypedContractMethod<[], [string[]], "view">;

  isManager: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  managers: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  proposeBudget: TypedContractMethod<
    [_recipient: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approvals"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "approveBudget"
  ): TypedContractMethod<[_budgetId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "budgets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, boolean, bigint, bigint] & {
        recipient: string;
        amount: bigint;
        released: boolean;
        approvals: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBudgetStatus"
  ): TypedContractMethod<
    [_budgetId: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        recipient: string;
        amount: bigint;
        approvalCount: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBudgets"
  ): TypedContractMethod<[], [MultiSigBudget.BudgetStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getmanagers"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "isManager"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "managers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "proposeBudget"
  ): TypedContractMethod<
    [_recipient: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BudgetApproved"
  ): TypedContractEvent<
    BudgetApprovedEvent.InputTuple,
    BudgetApprovedEvent.OutputTuple,
    BudgetApprovedEvent.OutputObject
  >;
  getEvent(
    key: "BudgetProposed"
  ): TypedContractEvent<
    BudgetProposedEvent.InputTuple,
    BudgetProposedEvent.OutputTuple,
    BudgetProposedEvent.OutputObject
  >;
  getEvent(
    key: "BudgetReleased"
  ): TypedContractEvent<
    BudgetReleasedEvent.InputTuple,
    BudgetReleasedEvent.OutputTuple,
    BudgetReleasedEvent.OutputObject
  >;
  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;

  filters: {
    "BudgetApproved(uint256,address)": TypedContractEvent<
      BudgetApprovedEvent.InputTuple,
      BudgetApprovedEvent.OutputTuple,
      BudgetApprovedEvent.OutputObject
    >;
    BudgetApproved: TypedContractEvent<
      BudgetApprovedEvent.InputTuple,
      BudgetApprovedEvent.OutputTuple,
      BudgetApprovedEvent.OutputObject
    >;

    "BudgetProposed(uint256,address,uint256)": TypedContractEvent<
      BudgetProposedEvent.InputTuple,
      BudgetProposedEvent.OutputTuple,
      BudgetProposedEvent.OutputObject
    >;
    BudgetProposed: TypedContractEvent<
      BudgetProposedEvent.InputTuple,
      BudgetProposedEvent.OutputTuple,
      BudgetProposedEvent.OutputObject
    >;

    "BudgetReleased(uint256,address,uint256)": TypedContractEvent<
      BudgetReleasedEvent.InputTuple,
      BudgetReleasedEvent.OutputTuple,
      BudgetReleasedEvent.OutputObject
    >;
    BudgetReleased: TypedContractEvent<
      BudgetReleasedEvent.InputTuple,
      BudgetReleasedEvent.OutputTuple,
      BudgetReleasedEvent.OutputObject
    >;

    "Deposit(address,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
  };
}
